default_platform(:ios)


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_AUTH_KEY_ID"],
      issuer_id: ENV["APPLE_AUTH_ISSUER_ID"],
      key_filepath: ENV["APPLE_AUTH_KEY_PATH"],
      duration: 500, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
      
    match(type: "appstore", app_identifier: "com.baptistelecat.weatherjourney", api_key: api_key)
    version_code = latest_testflight_build_number + 1
    sh("sh ../../deploy/deploy_ios.sh #{version_code.to_s}")
    upload_to_testflight(ipa: "../../weather_assistant/build/ios/ipa/weather_assistant.ipa")
  end

  lane :promote_to_app_store do
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_AUTH_KEY_ID"],
      issuer_id: ENV["APPLE_AUTH_ISSUER_ID"],
      key_filepath: ENV["APPLE_AUTH_KEY_PATH"],
      duration: 500, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
    deliver(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      run_precheck_before_submit: false
    )
  end
end
