# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    app_store_connect_api_key(
      key_id: "6Q5XDZTMC3",
      issuer_id: "2174b29f-1a4b-40d9-8f5a-7c4ed51a8189",
      key_filepath: "./AuthKey_PNJ6T5P4M5.p8",
      duration: 500, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
      
    match(type: "appstore", app_identifier: "com.baptistelecat.weatherjourney")
    version_code = latest_testflight_build_number + 1
    #build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    sh("cd ../../deploy && ./deploy_ios.sh #{version_code.to_s}")
    upload_to_testflight(ipa: "../build/ios/ipa/weather_assistant.ipa")
    #TODO IN CI upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
