default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_AUTH_KEY_ID"],
      issuer_id: ENV["APPLE_AUTH_ISSUER_ID"],
      key_filepath: ENV["APPLE_AUTH_KEY_PATH"],
      duration: 500, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
    
    match(type: "appstore", app_identifier: "com.baptistelecat.weatherjourney", api_key: api_key)
    
    # Get the current build number from TestFlight
    current_build_number = latest_testflight_build_number + 1

    # Increment the build number based on the latest build number from TestFlight
    increment_build_number(build_number: current_build_number)
    
    # If you want to increment the version number based on the latest version in the App Store
    # current_app_store_version = get_app_store_version_number
    # next_version_number = increment_version_number(version_number: current_app_store_version)

    # If you want to manually set the version number from the environment variable
    # increment_version_number(version_number: ENV["APP_VERSION"])

    # Build the app
    gym(
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "./build", # Specify the output directory here
      output_name: "weather_assistant.ipa", # Specify the output name here
      clean: true, # Clean the project before building
      include_bitcode: true # Include bitcode
    )
    
    # Upload the build to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true, # Skip waiting if in CI
      api_key: api_key
    )
  end
end
