name: BETA Deployment Workflow | PlayStore - TestFlight

on:
  workflow_dispatch:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.semver.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Create a MINOR commit
        run: |
          git config --local user.email "ci-executor@github.com"
          git config --local user.name "GitHub Action"
          git checkout develop
          git commit --allow-empty -m "(MINOR) Bump version"
          git push origin develop
        shell: bash

      - name: Semantic Versioning
        id: semver # Définissez un ID pour cette étape pour pouvoir récupérer les outputs
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: ${{ github.ref }}
          format: "${major}.${minor}.${patch}"
          tag_prefix: ""

      - name: Print new version
        run: echo "The new version is ${{ steps.semver.outputs.version }}"

      - name: Create a release branch for the new version from develop
        run: |
          git config --local user.email "ci-executor@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b release/${{ steps.semver.outputs.version }} develop
          git push origin release/${{ steps.semver.outputs.version }}

      - name: create a tag for the new version
        run: |
          git config --local user.email "ci-executor@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.semver.outputs.version }} -m "Release ${{ steps.semver.outputs.version }}"
          git push origin ${{ steps.semver.outputs.version }}

  build-and-deploy-android:
    needs: create-release-branch
    environment: beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags
          ref: release/${{ needs.create-release-branch.outputs.release_version }}

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          rubygems: latest

      - name: Install Firebase CLI
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Generate Firebase options
        run: |
          flutter pub global activate flutterfire_cli
          flutterfire configure --project=$FIREBASE_PROJECT_ID --android-package-name=$ANDROID_PACKAGE_NAME --platforms=android --yes
        shell: bash
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          ANDROID_PACKAGE_NAME: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}

      - name: Setup Android release key
        run: |
          echo ${{ secrets.KEY_BASE_64 }} | base64 --decode > android/app/key.jks
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > android/key.properties
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> android/key.properties
        shell: bash

      - name: Setup PlayStore service account
        run: |
          echo ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_BASE_64 }} | base64 --decode > android/playstore-service-account.json
        shell: bash

      - name: Deploy Android Beta to PlayStore via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta
          subdirectory: android

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weather_assistant.aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-and-deploy-ios:
    needs: create-release-branch
    environment: beta
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags
          ref: release/${{ needs.create-release-branch.outputs.release_version }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          rubygems: latest

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

      - name: Download AppleAuthKey and GCloud KeyFile Json from GCP bucket
        run: |
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.APPLE_AUTH_KEY_FILENAME }}' ./ios/'${{ secrets.APPLE_AUTH_KEY_FILENAME }}'
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}' ./ios/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}'
          ls

      - name: Install Setup AppStore files
        run: |
          flutter pub get
          cd ios
          pod cache clean --all
          bundle install
          bundle exec pod install
        shell: bash

      - name: Install Firebase CLI
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Generate Firebase options
        run: |
          flutter pub global activate flutterfire_cli
          flutterfire configure --project=$FIREBASE_PROJECT_ID --ios-bundle-id=$IOS_BUNDLE_ID --platforms=ios --yes
        shell: bash
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          IOS_BUNDLE_ID: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta
          subdirectory: ios
        env:
          DEVELOPER_APP_IDENTIFIER: "${{ secrets.DEVELOPER_APP_IDENTIFIER }}"
          APPLE_DEVELOPER_USERNAME: "${{ secrets.APPLE_DEVELOPER_USERNAME }}"
          APPLE_AUTH_KEY_ID: "${{ secrets.APPLE_AUTH_KEY_ID }}"
          APPLE_AUTH_ISSUER_ID: "${{ secrets.APPLE_AUTH_ISSUER_ID }}"
          APPLE_AUTH_KEY_PATH: "${{ secrets.APPLE_AUTH_KEY_PATH }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          APP_STORE_CONNECT_TEAM_ID: "${{ secrets.APP_STORE_CONNECT_TEAM_ID }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
          MATCH_KEYCHAIN_PASSWORD: "${{ secrets.MATCH_KEYCHAIN_PASSWORD }}"
          GOOGLE_CLOUD_BUCKET_NAME: "${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}"
          GOOGLE_CLOUD_PROJECT_ID: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weather_assistant.ipa
          path: build/ios/ipa/weather_assistant.ipa
