name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Test
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  update-develop-from-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Merge main into develop
        run: |
          git config --local user.email "ci-executor@github.com"
          git config --local user.name "GitHub Action"
          git checkout develop
          git merge origin/main
          git push origin develop
        shell: bash

  
          